In [80]:
#plot image in python console
%matplotlib inline  
%config InlineBackend.figure_format = 'svg'
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
plt.style.use('ggplot')

from pandas.plotting import scatter_matrix

import plotly
import plotly.offline as py
plotly.offline.init_notebook_mode(connected=True)
import plotly.graph_objs as go

In [137]:
df = pd.read_csv('points_world.csv')

/Users/jieanyan/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning:

Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.



In [138]:
df.head()

[-136.579  -122.034   -5.18907]
0  [-136.342  -122.063   -5.17105]
1  [-135.743  -122.299   -5.12567]
2  [-136.041  -122.322   -5.14822]
3  [-135.983  -122.034   -5.14387]
4  [-135.928   -122.17   -5.13965]

In [139]:
df.tail()

[-136.579   -122.034   -5.18907]
1241620   [-198.03   -111.618   -10.9265]
1241621   [-198.03       -nan   -10.9265]
1241622  [-176.102       -nan   -8.63512]
1241623      [-nan       -nan       -nan]
1241624      [-nan   -142.623       -nan]

In [140]:
#print(df.columns); used to get the column_head 
temp = df.columns.values
temp.shape

(3,)

In [141]:
new_row = pd.DataFrame(temp.reshape(1,3), columns = list(df.columns.values))#get the column head save it as a list
new_row
#type(new_row)

[-136.579   -122.034   -5.18907]
0  [-136.579   -122.034   -5.18907]

In [142]:
df = pd.concat((df,new_row), axis=0,ignore_index=True)# add the new line after the last row of the list

In [143]:
df.tail()

[-136.579   -122.034   -5.18907]
1241621   [-198.03       -nan   -10.9265]
1241622  [-176.102       -nan   -8.63512]
1241623      [-nan       -nan       -nan]
1241624      [-nan   -142.623       -nan]
1241625  [-136.579   -122.034   -5.18907]

In [133]:
df.columns= list('XYZ')#add column's head
df.head()

X        Y           Z
0  [-136.342 -122.063   -5.17105]
1  [-135.743 -122.299   -5.12567]
2  [-136.041 -122.322   -5.14822]
3  [-135.983 -122.034   -5.14387]
4  [-135.928  -122.17   -5.13965]

In [136]:
print(df.iloc[-1,1])  
print(df.iloc[-1,1][1:])

 -122.034
-122.034


In [124]:
df.iloc[-1,1] = float(df.iloc[-1,1][1:])

In [52]:
df.X = df.X.str.replace('[','')
df.X = df.X.apply(lambda x: float(x))

In [53]:
df.Z = df.Z.str.replace(']','')
df.Z = df.Z.apply(lambda z: float(z))

In [54]:
df.dropna(inplace=True) 
df.isna().sum()

X    0
Y    0
Z    0
dtype: int64

In [55]:
df.drop(df[df.Y == ' -nan'].index, inplace=True)

In [56]:
is_str = df.Y.apply(lambda x:type(x) == str)
is_str.value_counts()

False    1048577
True      192071
Name: Y, dtype: int64

In [57]:
df.Y = df.Y.apply(lambda x: x.strip() if type(x)==str else x)
df.Y = df.Y.astype(float)

In [58]:
is_str = df.Y.apply(lambda x:type(x) == str)
is_str.value_counts()

False    1240648
Name: Y, dtype: int64

In [61]:
# change the num here to select total number of points to plot
select_index = list(np.linspace(0, df.shape[0], num=120000, dtype= np.int64))
trace1 = go.Scatter3d(x=df['X'][select_index],
                    y=df['Y'][select_index],
                    z=df['Z'][select_index],
                    mode = 'markers',
                    marker = dict(size=1,opacity=0.3),
                   )

layout = go.Layout(dict(
                    scene = dict(
                        xaxis = dict(title='x'),
                        yaxis = dict(title='y'),
                        zaxis = dict(title='z'),
                            )
                        )
                  )

fig = go.Figure(data=[trace1], layout=layout)
# remove the # below and add # to the head of the subsequent row to use online plot
plotly.plotly.iplot(fig)
# py.iplot(fig)

/Users/jieanyan/anaconda3/lib/python3.6/site-packages/pandas/core/series.py:842: FutureWarning:


Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike

/Users/jieanyan/anaconda3/lib/python3.6/site-packages/plotly/plotly/plotly.py:230: UserWarning:

Woah there! Look at all those points! Due to browser limitations, the Plotly SVG drawing functions have a hard time graphing more than 500k data points for line charts, or 40k points for other types of charts. Here are some suggestions:
(1) Use the `plotly.graph_objs.Scattergl` trace object to generate a WebGl graph.
(2) Trying using the image API to return an image instead of a graph URL
(3) Use matplotlib
(4) See if you can create your visualization with fewer data points

If the visualization you're using aggregates points (e.g., box plot, his

The draw time for this plot will be slow for all clients.


/Users/jieanyan/anaconda3/lib/python3.6/site-packages/plotly/api/v1/clientresp.py:40: UserWarning:

Estimated Draw Time Too Long

